name : CI/CD for dummy react-app

on:
push:
branches: [main]
workflow_dispatch:

permissions:
contents: write

jobs:
build_and_deploy:
runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Step Node.js
  uses: actions/setup-node@v3  
  with: 
   node-version: 20

- name: Install dependencies  
  run: npm install

- name: Build Project
  run: npm runn build
     
